# -*- coding: utf-8 -*-
"""Carbon.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dhIAcic3eIuRWFRGq4Sbj3QPaJqTv-wE

Installing packages
"""

!pip install pandas matplotlib seaborn numpy scipy

"""importing necessary libraries"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""Loaded my CSV file into a pandas dataframe to start working with it"""

df = pd.read_csv('/content/emissions_medium_granularity.csv')

"""Taking a quick look at the first few rows and the overall structure of the data"""

df.head()

"""Taking a quick look at datatypes and missing values"""

df.info()

"""Removing any duplicate rows to avoid double-counting"""

# Remove duplicates if any
df = df.drop_duplicates()

"""Checking if there are missing values in any columns"""

# Check for missing values
print(df.isnull().sum())

"""Droping rows with missing values to clean the data"""

# Fill or remove missing values (example: drop rows with NaN)
df = df.dropna()

"""Making sure important columns have the correct data types for calculations"""

# Ensure consistent data types
df['year'] = df['year'].astype(int)
df['production_value'] = df['production_value'].astype(float)
df['total_emissions_MtCO2e'] = df['total_emissions_MtCO2e'].astype(float)

"""Converting units so everything is consistent"""

#  Standardize units
# Example: Convert Bcf to Million cubic meters (1 Bcf = 0.0283168 million m³)
df.loc[df['production_unit'] == 'Bcf/yr', 'production_value'] *= 0.0283168
df.loc[df['production_unit'] == 'Bcf/yr', 'production_unit'] = 'Million m3/yr'

"""Calculating emissions per unit of production for each row"""

# Create Emission Intensity
df['emission_intensity'] = df['total_emissions_MtCO2e'] / df['production_value']

""" Sum of total emissions for each year"""

# Summary Statistics
# Total emissions per year
total_emissions_year = df.groupby('year')['total_emissions_MtCO2e'].sum().reset_index()
total_emissions_year

"""Sum total emissions for each type of commodity"""

# Emissions by commodity
emissions_by_commodity = df.groupby('commodity')['total_emissions_MtCO2e'].sum().reset_index()
emissions_by_commodity

"""Ploting total emissions over the years"""

sns.set_style("whitegrid")

# Time series of total emissions
plt.figure(figsize=(12,6))
sns.lineplot(data=total_emissions_year, x='year', y='total_emissions_MtCO2e', marker='o')
plt.title('Total Emissions Over Time')
plt.ylabel('Total Emissions (MtCO2e)')
plt.xlabel('Year')
plt.show()

"""Ploting emissions by commodity over time"""

#  Emissions by commodity over time
plt.figure(figsize=(12,6))
sns.lineplot(data=df, x='year', y='total_emissions_MtCO2e', hue='commodity', marker='o')
plt.title('Emissions by Commodity Over Time')
plt.ylabel('Total Emissions (MtCO2e)')
plt.xlabel('Year')
plt.show()

"""Ploting emissions of top companies over time"""

# Top emitting companies per year
top_companies = df.groupby(['year','parent_entity'])['total_emissions_MtCO2e'].sum().reset_index()
plt.figure(figsize=(12,6))
sns.lineplot(data=top_companies, x='year', y='total_emissions_MtCO2e', hue='parent_entity', marker='o')
plt.title('Emissions by Company Over Time')
plt.ylabel('Total Emissions (MtCO2e)')
plt.xlabel('Year')
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.show()

"""Saving the cleaned and processed dataset to a new CSV file"""

df.to_csv('cleaned_carbon_data.csv', index=False)
print("Cleaned dataset saved as 'cleaned_carbon_data.csv'")

"""GHG Protocol Scope Categorization

According to the GHG Protocol Corporate Standard (WRI & WBCSD, 2004), emissions are categorized into three scopes:
- Scope 1: Direct emissions from owned/controlled sources (e.g., fuel combustion)
- Scope 2: Indirect emissions from purchased energy
- Scope 3: All other indirect value chain emissions

This dataset represents primarily Scope 1 & 3 upstream production emissions from the Carbon Majors dataset.
"""

# Categorize emissions by GHG Protocol Scopes
# This dataset represents production-based emissions (Scope 1 & 3 upstream)

# Add scope categorization column
df['ghg_scope'] = 'Scope 1 & 3 (Upstream Production)'

# Summary of emissions by scope category
print("=== GHG PROTOCOL SCOPE CATEGORIZATION ===")
print(f"Total Emissions in Dataset: {df['total_emissions_MtCO2e'].sum():.2f} MtCO2e")
print(f"Scope Category: {df['ghg_scope'].unique()[0]}")
print(f"Temporal Coverage: {df['year'].min()} - {df['year'].max()}")
print(f"Number of Entities: {df['parent_entity'].nunique()}")
print(f"Number of Commodities: {df['commodity'].nunique()}")

"""Green Ledger - Emission Intensity Metrics

Following the Green Ledger Imperative (Position Green, 2023), we integrate GHG metrics with financial analogs:
- GHG Emissions ≈ Cost of Goods Sold (COGS)
- GHG Intensity ≈ Gross Margin (efficiency metric)

This establishes the financially actionable link between emissions and operational costs.
"""

# Enhanced Emission Intensity Analysis (already calculated above, now analyzing)
print("=== GREEN LEDGER: EMISSION INTENSITY METRICS ===\n")

# Overall emission intensity statistics
print("Emission Intensity Statistics (MtCO2e per production unit):")
print(df['emission_intensity'].describe())

# Emission intensity by commodity
print("\n--- Emission Intensity by Commodity ---")
intensity_by_commodity = df.groupby('commodity').agg({
    'emission_intensity': ['mean', 'median', 'std'],
    'total_emissions_MtCO2e': 'sum'
}).round(4)
print(intensity_by_commodity)

# Emission intensity by parent type (State vs Investor-owned)
print("\n--- Emission Intensity by Parent Type ---")
intensity_by_type = df.groupby('parent_type').agg({
    'emission_intensity': ['mean', 'median'],
    'total_emissions_MtCO2e': 'sum',
    'parent_entity': 'nunique'
}).round(4)
print(intensity_by_type)

# Identify most efficient vs least efficient entities
print("\n--- Top 10 Most Efficient Entities (Lowest Emission Intensity) ---")
most_efficient = df.groupby('parent_entity')['emission_intensity'].mean().nsmallest(10)
print(most_efficient)

print("\n--- Top 10 Least Efficient Entities (Highest Emission Intensity) ---")
least_efficient = df.groupby('parent_entity')['emission_intensity'].mean().nlargest(10)
print(least_efficient)

"""Entity Type Comparative Analysis

Comparing State-owned Entities vs Investor-owned Companies (Methodology Section 2.2)
"""

# Comparative analysis: State-owned vs Investor-owned entities
entity_comparison = df.groupby('parent_type').agg({
    'total_emissions_MtCO2e': ['sum', 'mean'],
    'production_value': ['sum', 'mean'],
    'emission_intensity': 'mean',
    'parent_entity': 'nunique'
}).round(2)

print("=== STATE-OWNED vs INVESTOR-OWNED COMPARISON ===")
print(entity_comparison)

# Calculate percentage share
total_emissions = df['total_emissions_MtCO2e'].sum()
emissions_by_type = df.groupby('parent_type')['total_emissions_MtCO2e'].sum()
print("\n--- Percentage Share of Total Emissions ---")
for entity_type, emissions in emissions_by_type.items():
    percentage = (emissions / total_emissions) * 100
    print(f"{entity_type}: {percentage:.2f}%")

# Visualization: Emissions by Entity Type over Time
plt.figure(figsize=(14, 6))
entity_type_time = df.groupby(['year', 'parent_type'])['total_emissions_MtCO2e'].sum().reset_index()
sns.lineplot(data=entity_type_time, x='year', y='total_emissions_MtCO2e', hue='parent_type', marker='o', linewidth=2.5)
plt.title('Emissions by Entity Type Over Time (1962-2022)', fontsize=16, fontweight='bold')
plt.ylabel('Total Emissions (MtCO2e)', fontsize=12)
plt.xlabel('Year', fontsize=12)
plt.legend(title='Entity Type', fontsize=10)
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

"""Temporal Trend Analysis (CRISP-DM)

Year-over-Year growth calculations and trend identification across the 60-year dataset (1962-2022)
"""

# Year-over-Year (YoY) Growth Analysis
yearly_emissions = df.groupby('year')['total_emissions_MtCO2e'].sum().reset_index()
yearly_emissions['YoY_Change'] = yearly_emissions['total_emissions_MtCO2e'].diff()
yearly_emissions['YoY_Pct_Change'] = yearly_emissions['total_emissions_MtCO2e'].pct_change() * 100

print("=== TEMPORAL TREND ANALYSIS (1962-2022) ===\n")

# Identify key inflection points
print("--- Top 5 Years with Highest Emissions ---")
print(yearly_emissions.nlargest(5, 'total_emissions_MtCO2e')[['year', 'total_emissions_MtCO2e']])

print("\n--- Top 5 Years with Largest YoY Increase ---")
print(yearly_emissions.nlargest(5, 'YoY_Change')[['year', 'YoY_Change', 'YoY_Pct_Change']])

print("\n--- Top 5 Years with Largest YoY Decrease ---")
print(yearly_emissions.nsmallest(5, 'YoY_Change')[['year', 'YoY_Change', 'YoY_Pct_Change']])

# Decadal Analysis
yearly_emissions['decade'] = (yearly_emissions['year'] // 10) * 10
decade_summary = yearly_emissions.groupby('decade').agg({
    'total_emissions_MtCO2e': ['mean', 'sum'],
    'YoY_Pct_Change': 'mean'
}).round(2)
print("\n--- Emissions by Decade ---")
print(decade_summary)

# Visualization: YoY Growth Rate
fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(14, 10))

# Plot 1: Total Emissions Over Time
ax1.plot(yearly_emissions['year'], yearly_emissions['total_emissions_MtCO2e'],
         marker='o', linewidth=2, color='darkred')
ax1.set_title('Total Global Emissions Over Time (1962-2022)', fontsize=16, fontweight='bold')
ax1.set_ylabel('Total Emissions (MtCO2e)', fontsize=12)
ax1.set_xlabel('Year', fontsize=12)
ax1.grid(True, alpha=0.3)

# Plot 2: Year-over-Year Percentage Change
ax2.bar(yearly_emissions['year'], yearly_emissions['YoY_Pct_Change'],
        color=['green' if x < 0 else 'red' for x in yearly_emissions['YoY_Pct_Change']], alpha=0.7)
ax2.axhline(y=0, color='black', linestyle='-', linewidth=0.8)
ax2.set_title('Year-over-Year Percentage Change in Emissions', fontsize=16, fontweight='bold')
ax2.set_ylabel('YoY % Change', fontsize=12)
ax2.set_xlabel('Year', fontsize=12)
ax2.grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

"""Top Emitters Dashboard - Schneiderman's Visual Seeking Mantra

"Overview first, zoom and filter, then details-on-demand" (Schneiderman, 1996)

Big Number Cards: Global totals and top 3 polluting entities of all time
"""

# Cumulative Emissions by Entity (All Time)
cumulative_emissions = df.groupby('parent_entity').agg({
    'total_emissions_MtCO2e': 'sum',
    'production_value': 'sum',
    'emission_intensity': 'mean',
    'parent_type': 'first'
}).reset_index()
cumulative_emissions = cumulative_emissions.sort_values('total_emissions_MtCO2e', ascending=False)

# Calculate market share
total_global_emissions = cumulative_emissions['total_emissions_MtCO2e'].sum()
cumulative_emissions['market_share_pct'] = (cumulative_emissions['total_emissions_MtCO2e'] / total_global_emissions) * 100
cumulative_emissions['cumulative_share_pct'] = cumulative_emissions['market_share_pct'].cumsum()

print("=" * 80)
print("BIG NUMBER CARDS - OVERVIEW DASHBOARD")
print("=" * 80)
print(f"\nGLOBAL TOTAL EMISSIONS (1962-2022): {total_global_emissions:,.2f} MtCO2e")
print(f"Temporal Coverage: {df['year'].min()} - {df['year'].max()} ({df['year'].max() - df['year'].min() + 1} years)")
print(f"Total Entities Tracked: {df['parent_entity'].nunique()}")
print(f"Total Commodities: {df['commodity'].nunique()}")

print("\n" + "=" * 80)
print("TOP 10 CARBON MAJORS (Cumulative Emissions All-Time)")
print("=" * 80)
top_10 = cumulative_emissions.head(10)
for idx, row in top_10.iterrows():
    print(f"{cumulative_emissions.index.get_loc(idx) + 1}. {row['parent_entity']}")
    print(f"   Emissions: {row['total_emissions_MtCO2e']:,.2f} MtCO2e | Market Share: {row['market_share_pct']:.2f}%")
    print(f"   Type: {row['parent_type']} | Avg Intensity: {row['emission_intensity']:.4f}")
    print()

# Concentration Analysis
top_5_share = cumulative_emissions.head(5)['market_share_pct'].sum()
top_10_share = cumulative_emissions.head(10)['market_share_pct'].sum()
top_20_share = cumulative_emissions.head(20)['market_share_pct'].sum()

print("=" * 80)
print("MARKET CONCENTRATION ANALYSIS")
print("=" * 80)
print(f"Top 5 entities control: {top_5_share:.2f}% of total emissions")
print(f"Top 10 entities control: {top_10_share:.2f}% of total emissions")
print(f"Top 20 entities control: {top_20_share:.2f}% of total emissions")

# Visualization: Top 15 Emitters
plt.figure(figsize=(14, 8))
top_15 = cumulative_emissions.head(15)
colors = ['#8B0000' if i < 3 else '#DC143C' if i < 10 else '#FF6347' for i in range(15)]
bars = plt.barh(range(15), top_15['total_emissions_MtCO2e'], color=colors, alpha=0.8)
plt.yticks(range(15), top_15['parent_entity'], fontsize=10)
plt.xlabel('Cumulative Emissions (MtCO2e)', fontsize=12, fontweight='bold')
plt.title('Top 15 Carbon Majors - Cumulative Emissions (1962-2022)', fontsize=16, fontweight='bold')
plt.gca().invert_yaxis()

# Add value labels
for i, (idx, row) in enumerate(top_15.iterrows()):
    plt.text(row['total_emissions_MtCO2e'], i, f" {row['total_emissions_MtCO2e']:,.0f}",
             va='center', fontsize=9)

plt.grid(axis='x', alpha=0.3)
plt.tight_layout()
plt.show()

"""Commodity Breakdown Analysis - Diagnostic Analytics

Stacked area charts revealing drivers of emissions by fuel type (Section 2.4)
"""

# Emissions by Commodity Analysis
commodity_summary = df.groupby('commodity').agg({
    'total_emissions_MtCO2e': ['sum', 'mean'],
    'production_value': 'sum',
    'emission_intensity': 'mean',
    'parent_entity': 'nunique'
}).round(2)

print("=" * 80)
print("COMMODITY BREAKDOWN ANALYSIS")
print("=" * 80)
print(commodity_summary)

# Calculate commodity percentage share
commodity_share = df.groupby('commodity')['total_emissions_MtCO2e'].sum().sort_values(ascending=False)
print("\n--- Percentage Share by Commodity ---")
for commodity, emissions in commodity_share.items():
    pct = (emissions / total_global_emissions) * 100
    print(f"{commodity}: {emissions:,.2f} MtCO2e ({pct:.2f}%)")

# Time series by commodity
commodity_time = df.groupby(['year', 'commodity'])['total_emissions_MtCO2e'].sum().reset_index()
commodity_pivot = commodity_time.pivot(index='year', columns='commodity', values='total_emissions_MtCO2e').fillna(0)

# Stacked Area Chart
plt.figure(figsize=(14, 7))
plt.stackplot(commodity_pivot.index,
              [commodity_pivot[col] for col in commodity_pivot.columns],
              labels=commodity_pivot.columns,
              alpha=0.8)
plt.title('Emissions by Commodity Over Time (Stacked)', fontsize=16, fontweight='bold')
plt.ylabel('Total Emissions (MtCO2e)', fontsize=12)
plt.xlabel('Year', fontsize=12)
plt.legend(loc='upper left', fontsize=10)
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

# Individual commodity trends
fig, axes = plt.subplots(1, len(commodity_pivot.columns), figsize=(18, 5))
if len(commodity_pivot.columns) == 1:
    axes = [axes]

for idx, commodity in enumerate(commodity_pivot.columns):
    axes[idx].plot(commodity_pivot.index, commodity_pivot[commodity],
                   linewidth=2, marker='o', markersize=3)
    axes[idx].set_title(f'{commodity}', fontsize=12, fontweight='bold')
    axes[idx].set_ylabel('Emissions (MtCO2e)', fontsize=10)
    axes[idx].set_xlabel('Year', fontsize=10)
    axes[idx].grid(True, alpha=0.3)

plt.suptitle('Individual Commodity Emission Trends', fontsize=16, fontweight='bold', y=1.02)
plt.tight_layout()
plt.show()

"""Data Quality & Carbon Integrity Index (CIX) Assessment


The Carbon Integrity Index evaluates:
1. Data Completeness
2. Methodological Transparency
3. Uncertainty Assessment
4. Traceability
"""

# Data Quality Assessment - CIX Alignment
print("=" * 80)
print("DATA QUALITY & CARBON INTEGRITY INDEX (CIX) ASSESSMENT")
print("=" * 80)

# 1. Data Completeness Check
print("\n--- 1. DATA COMPLETENESS ---")
total_records = len(df)
print(f"Total Records: {total_records:,}")
print(f"Records after cleaning: {total_records:,}")
print(f"\nMissing Values by Column:")
missing_summary = df.isnull().sum()
for col, missing in missing_summary.items():
    if missing > 0:
        print(f"  {col}: {missing} ({missing/total_records*100:.2f}%)")
    else:
        print(f"  {col}: 0 (0.00%)")

# 2. Temporal Coverage
print("\n--- 2. TEMPORAL COVERAGE ---")
year_coverage = df.groupby('year').size()
missing_years = set(range(df['year'].min(), df['year'].max() + 1)) - set(df['year'].unique())
print(f"Year Range: {df['year'].min()} - {df['year'].max()}")
print(f"Total Years: {len(year_coverage)}")
print(f"Missing Years: {len(missing_years)} - {sorted(missing_years) if missing_years else 'None'}")

# 3. Entity Coverage
print("\n--- 3. ENTITY COVERAGE ---")
entity_coverage = df.groupby('parent_entity').agg({
    'year': ['min', 'max', 'count']
})
print(f"Total Unique Entities: {df['parent_entity'].nunique()}")
entities_with_full_coverage = entity_coverage[
    (entity_coverage[('year', 'max')] - entity_coverage[('year', 'min')] + 1) ==
    entity_coverage[('year', 'count')]
]
print(f"Entities with continuous yearly data: {len(entities_with_full_coverage)}")

# 4. Data Validation - Outlier Detection
print("\n--- 4. OUTLIER DETECTION ---")
Q1 = df['total_emissions_MtCO2e'].quantile(0.25)
Q3 = df['total_emissions_MtCO2e'].quantile(0.75)
IQR = Q3 - Q1
outliers = df[(df['total_emissions_MtCO2e'] < (Q1 - 1.5 * IQR)) |
              (df['total_emissions_MtCO2e'] > (Q3 + 1.5 * IQR))]
print(f"Statistical Outliers (IQR method): {len(outliers)} records ({len(outliers)/total_records*100:.2f}%)")
print(f"Max Emission Value: {df['total_emissions_MtCO2e'].max():.2f} MtCO2e")
print(f"Min Emission Value: {df['total_emissions_MtCO2e'].min():.2f} MtCO2e")

# 5. Consistency Checks
print("\n--- 5. CONSISTENCY CHECKS ---")
negative_emissions = df[df['total_emissions_MtCO2e'] < 0]
negative_production = df[df['production_value'] < 0]
print(f"Records with negative emissions: {len(negative_emissions)}" if len(negative_emissions) == 0 else f"Warning: {len(negative_emissions)} records")
print(f"Records with negative production: {len(negative_production)}" if len(negative_production) == 0 else f"Warning: {len(negative_production)} records")

# Check emission intensity reasonableness
inf_intensity = df[df['emission_intensity'].isin([float('inf'), float('-inf')])]
print(f"Records with infinite emission intensity: {len(inf_intensity)}" if len(inf_intensity) == 0 else f"Warning: {len(inf_intensity)} records")

# 6. CIX Score Estimation
print("\n" + "=" * 80)
print("ESTIMATED CIX SCORE COMPONENTS (0-1 scale)")
print("=" * 80)

completeness_score = 1 - (df.isnull().sum().sum() / (len(df) * len(df.columns)))
temporal_score = 1 - (len(missing_years) / (df['year'].max() - df['year'].min() + 1))
consistency_score = 1 - ((len(negative_emissions) + len(negative_production) + len(inf_intensity)) / total_records)
outlier_score = 1 - (len(outliers) / total_records)

print(f"Completeness Score: {completeness_score:.3f}")
print(f"Temporal Coverage Score: {temporal_score:.3f}")
print(f"Consistency Score: {consistency_score:.3f}")
print(f"Outlier Management Score: {outlier_score:.3f}")
print(f"\nOverall Data Quality Score: {(completeness_score + temporal_score + consistency_score + outlier_score) / 4:.3f}")

print("\nNote: According to Di Vaio et al. (2024), the average CIX score for large companies is 5.7/10.")
print("This dataset demonstrates high quality with minimal missing data and strong temporal coverage.")

"""Production vs Emissions Correlation Analysis

Diagnostic Analytics - Identifying efficiency outliers (Section 2.4)
"""

# Production vs Emissions Correlation
import numpy as np
from scipy import stats

print("=" * 80)
print("PRODUCTION vs EMISSIONS CORRELATION ANALYSIS")
print("=" * 80)

# Overall correlation
correlation, p_value = stats.pearsonr(df['production_value'], df['total_emissions_MtCO2e'])
print(f"\nOverall Pearson Correlation: {correlation:.4f}")
print(f"P-value: {p_value:.2e}")
print(f"Interpretation: {'Strong positive' if correlation > 0.7 else 'Moderate positive' if correlation > 0.4 else 'Weak'} correlation")

# Correlation by commodity
print("\n--- Correlation by Commodity ---")
for commodity in df['commodity'].unique():
    commodity_df = df[df['commodity'] == commodity]
    if len(commodity_df) > 2:
        corr, pval = stats.pearsonr(commodity_df['production_value'],
                                     commodity_df['total_emissions_MtCO2e'])
        print(f"{commodity}: r = {corr:.4f} (p = {pval:.2e})")

# Identify efficiency outliers (entities with high production but low emissions)
entity_summary = df.groupby('parent_entity').agg({
    'production_value': 'sum',
    'total_emissions_MtCO2e': 'sum',
    'emission_intensity': 'mean'
}).reset_index()

# Calculate z-scores for efficiency analysis
entity_summary['production_zscore'] = stats.zscore(entity_summary['production_value'])
entity_summary['emissions_zscore'] = stats.zscore(entity_summary['total_emissions_MtCO2e'])
entity_summary['efficiency_gap'] = entity_summary['production_zscore'] - entity_summary['emissions_zscore']

# High production, low emissions (efficient)
efficient_outliers = entity_summary.nlargest(5, 'efficiency_gap')
print("\n--- Top 5 Most Efficient Outliers (High Production, Lower Emissions) ---")
for idx, row in efficient_outliers.iterrows():
    print(f"{row['parent_entity']}: Efficiency Gap = {row['efficiency_gap']:.2f}")

# Low production, high emissions (inefficient)
inefficient_outliers = entity_summary.nsmallest(5, 'efficiency_gap')
print("\n--- Top 5 Least Efficient Outliers (Low Production, Higher Emissions) ---")
for idx, row in inefficient_outliers.iterrows():
    print(f"{row['parent_entity']}: Efficiency Gap = {row['efficiency_gap']:.2f}")

# Scatter plot: Production vs Emissions
fig, axes = plt.subplots(1, 2, figsize=(16, 6))

# Plot 1: Overall scatter
axes[0].scatter(df['production_value'], df['total_emissions_MtCO2e'],
                alpha=0.5, s=10, c='darkblue')
axes[0].set_xlabel('Production Value', fontsize=12)
axes[0].set_ylabel('Total Emissions (MtCO2e)', fontsize=12)
axes[0].set_title('Production vs Emissions (All Records)', fontsize=14, fontweight='bold')
axes[0].grid(True, alpha=0.3)

# Add regression line
z = np.polyfit(df['production_value'], df['total_emissions_MtCO2e'], 1)
p = np.poly1d(z)
axes[0].plot(df['production_value'].sort_values(),
             p(df['production_value'].sort_values()),
             "r--", linewidth=2, label=f'y={z[0]:.4f}x+{z[1]:.2f}')
axes[0].legend()

# Plot 2: By commodity
for commodity in df['commodity'].unique():
    commodity_df = df[df['commodity'] == commodity]
    axes[1].scatter(commodity_df['production_value'],
                   commodity_df['total_emissions_MtCO2e'],
                   alpha=0.6, s=15, label=commodity)

axes[1].set_xlabel('Production Value', fontsize=12)
axes[1].set_ylabel('Total Emissions (MtCO2e)', fontsize=12)
axes[1].set_title('Production vs Emissions by Commodity', fontsize=14, fontweight='bold')
axes[1].legend(fontsize=10)
axes[1].grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

# Emission Intensity Distribution
plt.figure(figsize=(14, 5))
plt.subplot(1, 2, 1)
plt.hist(df['emission_intensity'], bins=50, color='teal', alpha=0.7, edgecolor='black')
plt.xlabel('Emission Intensity', fontsize=12)
plt.ylabel('Frequency', fontsize=12)
plt.title('Distribution of Emission Intensity', fontsize=14, fontweight='bold')
plt.grid(axis='y', alpha=0.3)

plt.subplot(1, 2, 2)
df.boxplot(column='emission_intensity', by='commodity', figsize=(14, 5))
plt.suptitle('')
plt.title('Emission Intensity by Commodity', fontsize=14, fontweight='bold')
plt.ylabel('Emission Intensity', fontsize=12)
plt.xlabel('Commodity', fontsize=12)

plt.tight_layout()
plt.show()

"""Comprehensive Summary Statistics Dashboard

CRISP-DM Evaluation Phase - Complete statistical overview
"""

# Comprehensive Summary Statistics
print("=" * 90)
print(" " * 20 + "EXECUTIVE SUMMARY STATISTICS DASHBOARD")
print("=" * 90)

# Global Overview
print("\nGLOBAL METRICS (1962-2022)")
print("-" * 90)
print(f"Total Cumulative Emissions:        {df['total_emissions_MtCO2e'].sum():>20,.2f} MtCO2e")
print(f"Average Annual Emissions:          {df.groupby('year')['total_emissions_MtCO2e'].sum().mean():>20,.2f} MtCO2e/year")
print(f"Peak Year:                         {df.groupby('year')['total_emissions_MtCO2e'].sum().idxmax():>20}")
print(f"Peak Year Emissions:               {df.groupby('year')['total_emissions_MtCO2e'].sum().max():>20,.2f} MtCO2e")
print(f"Total Production Value:            {df['production_value'].sum():>20,.2f}")
print(f"Average Emission Intensity:        {df['emission_intensity'].mean():>20,.6f}")

# Temporal Statistics
print("\nTEMPORAL STATISTICS")
print("-" * 90)
yearly_stats = df.groupby('year')['total_emissions_MtCO2e'].sum()
print(f"Years Covered:                     {df['year'].min()} - {df['year'].max()} ({df['year'].max() - df['year'].min() + 1} years)")
print(f"Median Annual Emissions:           {yearly_stats.median():>20,.2f} MtCO2e")
print(f"Std Dev (Annual):                  {yearly_stats.std():>20,.2f} MtCO2e")
print(f"First Decade Avg (1960s):          {df[df['year'] < 1970]['total_emissions_MtCO2e'].mean():>20,.2f} MtCO2e")
print(f"Last Decade Avg (2020s):           {df[df['year'] >= 2020]['total_emissions_MtCO2e'].mean():>20,.2f} MtCO2e")

# Entity Statistics
print("\nENTITY STATISTICS")
print("-" * 90)
print(f"Total Unique Entities:             {df['parent_entity'].nunique():>20,}")
print(f"State-owned Entities:              {df[df['parent_type']=='State-owned Entity']['parent_entity'].nunique():>20,}")
print(f"Investor-owned Companies:          {df[df['parent_type']=='Investor-owned Company']['parent_entity'].nunique():>20,}")
print(f"Average Emissions per Entity:      {cumulative_emissions['total_emissions_MtCO2e'].mean():>20,.2f} MtCO2e")
print(f"Median Emissions per Entity:       {cumulative_emissions['total_emissions_MtCO2e'].median():>20,.2f} MtCO2e")
print(f"Top Entity (All-Time):             {cumulative_emissions.iloc[0]['parent_entity']:>20}")
print(f"Top Entity Emissions:              {cumulative_emissions.iloc[0]['total_emissions_MtCO2e']:>20,.2f} MtCO2e")

# Commodity Statistics
print("\nCOMMODITY STATISTICS")
print("-" * 90)
for commodity in df['commodity'].unique():
    commodity_data = df[df['commodity'] == commodity]
    total = commodity_data['total_emissions_MtCO2e'].sum()
    pct = (total / df['total_emissions_MtCO2e'].sum()) * 100
    print(f"{commodity:30} {total:>20,.2f} MtCO2e ({pct:>6.2f}%)")

# Distribution Statistics
print("\nDISTRIBUTION STATISTICS")
print("-" * 90)
print("\nEmissions per Record:")
print(df['total_emissions_MtCO2e'].describe().to_string())

print("\n\nEmission Intensity:")
print(df['emission_intensity'].describe().to_string())

# Growth Metrics
first_5_years = df[df['year'] <= df['year'].min() + 4]['total_emissions_MtCO2e'].sum()
last_5_years = df[df['year'] >= df['year'].max() - 4]['total_emissions_MtCO2e'].sum()
growth_rate = ((last_5_years - first_5_years) / first_5_years) * 100

print("\n\nGROWTH METRICS")
print("-" * 90)
print(f"First 5 Years Total (1962-1966):   {first_5_years:>20,.2f} MtCO2e")
print(f"Last 5 Years Total (2018-2022):    {last_5_years:>20,.2f} MtCO2e")
print(f"Overall Growth:                    {growth_rate:>20,.2f}%")
print(f"CAGR (Approx):                     {(growth_rate / (df['year'].max() - df['year'].min())):>20,.2f}% per year")

print("\n" + "=" * 90)
print(" " * 30 + "END OF SUMMARY DASHBOARD")
print("=" * 90)